name = "tracewise-api"
main = "src/main.js"
compatibility_date = "2026-06-05"
workers_dev = true

[vars]
AUTH_REQUIRED = "true"
DEMO_LOGIN_ENABLED = "true"
SESSION_COOKIE_SAMESITE = "none"
SESSION_COOKIE_SECURE = "true"
OPENAI_MODEL = "gpt-4o-mini"
ALLOW_FALLBACK_AI = "true"

[[d1_databases]]
binding = "DB"
database_name = "tracewise-db"
database_id = "83d58315-7183-49db-89df-3976f9f3b01d"

[env.production.vars]
AUTH_REQUIRED = "true"
DEMO_LOGIN_ENABLED = "false"
SESSION_COOKIE_SAMESITE = "none"
SESSION_COOKIE_SECURE = "true"
ALLOW_FALLBACK_AI = "true"
